#! /bin/sh

cd $(dirname $0)
DIR=$(pwd)

source $DIR/panel_config

if [ $(pgrep -cx panel) -gt 1 ] ; then
	pkill -o panel
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# remove any existing fifos
[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# match panel height to padding left by wm
bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -i "$CLOCK_INTERVAL" -sf 'C[%a %b %d] %l:%M %P' > "$PANEL_FIFO" &

# build font options and arguments
#font_opts=""
#for font in "${PANEL_FONT_FAMILY[@]}"; do
#	font_opts="$font_opts -f '$font'"
#done

cat "$PANEL_FIFO" \
	| ./panel_bar \
	| bar \
		-g "$PANEL_GEOMETRY" \
		-f "$PANEL_FONT_FAMILY" \
		-F "$COLOR_FG" \
		-B "$COLOR_BG" &

wait
