#! /bin/sh
#
# panel for LemonBoy's bar
#
# NOTE: items that are on different timers must be contained in separate variables

source $(dirname $0)/config

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		V*)
			# volume output
			volume_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
			;;
		N*)
			# wireless output
			wifi_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
			;;
		B*)
			# battery output
			name=${line#?}
			case $name in
				0*)
					bat0_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${name#?} %{B-}%{F-}"
					;;
				1*)
					bat1_info="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${name#?} %{B-}%{F-}"
					;;
			esac
			;;
		C*)
			# clock output
			sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?} %{B-}%{F-}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
                case $item in
                    [OFUofu]*)
                        # desktops
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                desk="%{F$COLOR_FOCUSED_OCCUPIED_FG}%{B$COLOR_FOCUSED_OCCUPIED_BG}${PAD}${name}${PAD}%{B-}%{F-}"
                                ;;
                            F*)
                                # focused free desktop
                                desk="%{F$COLOR_FOCUSED_FREE_FG}%{B$COLOR_FOCUSED_FREE_BG}${PAD}${name}${PAD}%{B-}%{F-}"
                                ;;
                            U*)
                                # focused urgent desktop
                                desk="%{F$COLOR_FOCUSED_URGENT_FG}%{B$COLOR_FOCUSED_URGENT_BG}${PAD}${name}${PAD}%{B-}%{F-}"
                                ;;
                            o*)
                                # occupied desktop
                                desk="%{F$COLOR_OCCUPIED_FG}%{B$COLOR_OCCUPIED_BG}${PAD}${name}${PAD}%{B-}%{F-}"
                                ;;
                            f*)
                                # free desktop
                                desk="%{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}${PAD}${name}${PAD}%{B-}%{F-}"
                                ;;
                            u*)
                                # urgent desktop
                                desk="%{F$COLOR_URGENT_FG}%{B$COLOR_URGENT_BG}${PAD}${name}${PAD}%{B-}%{F-}"
                                ;;
                        esac
                        # create clickable area
                        wm_infos="${wm_infos}%{A:bspc desktop -f ${name}:}${desk}%{A}"
                        ;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm_infos}%{c}${title}%{r}${wifi_info}${SEP}${volume_info}${SEP}${bat0_info}${SEP}${bat1_info}${SEP}${sys_infos}"
done
