#! /bin/sh

# config options
bspc config border_width       4
bspc config window_gap         6
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config auto_cancel           true
# NOTE: (top) padding is set by panel

# desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc desktop ^2 -l monocle

# rules
bspc rule -a Firefox        desktop=^2  follow=on
bspc rule -a Zathura        desktop=^3
bspc rule -a MPlayer        desktop=^5  follow=on floating=on
bspc rule -a Gimp           desktop=^8  follow=on floating=on
bspc rule -a libreoffice    desktop=^4  follow=on

# colors
bspc config focused_border_color        "#2aa198"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"
bspc config focused_locked_border_color "#00c7d8"
bspc config normal_locked_border_color  "#708d8f"
bspc config active_locked_border_color  "#808c8d"
bspc config urgent_border_color         "#cb4b16"
bspc config presel_border_color         "#cb4b16"

# Set pointer
xsetroot -cursor_name left_ptr &

# start panel
#~/.config/bspwm/panel/panel &
